### ISSUE TITLE
Duplicate field / Duplicate typename - With Vite/SvelteKit

### ISSUE THREAD

**Issue by pixelmund** [hayes/pothos#49]
Hey

Im running into issues with vite/sveltekit when i save a resolver file, i think because of some module caching in vite, idk the exact reason. 
I managed to work around the `Error: Duplicate typename: Another type with name LoginInput already exists.` by

```ts
if (import.meta.env.DEV) {
   builder.configStore.typeConfigs.clear();
}
```

But then the next error was `Error: Duplicate field definition for field email in LoginInput`. 

I don't know if maybe exposing a way to clear the configStore would be enough.

I can't really use giraphql without restarting the dev server which is not very productive.

**Comment by hayes** [comment]
This kinda makes sense.  I think what I could do is provide a setting that allows re-defining fields and types for use with module reloading.  The builder is stateful, which means its not ideal for module reloading.  If there is a way to always re-load a specific file on change reloading the file that defines the schema builder should work.  I'll see if there is an easy fix later today or tomorrow.

**Comment by hayes** [comment]
@pixelmund looked into this a bit.  I don't see a good way that is reliably safe to just clear the cache.  There is another (relatively simple) work around that should work.

I don't know exactly how you structured your graphql/giraphql code, but if you dynamically import your schema into the file that defines your builder everything should just work.

I set up tiny example to test this out here: https://github.com/hayes/svelekit-graphql-test/tree/main/src/graphql 

I haven't done any thorough testing, but I am fairly confident this should work reliably.  Let me know if this works, or if you have any issues!

**Comment by hayes** [comment]
For context on why the above suggestion should work:

When a file changes, the dev server clears the file that changed, along with everything that imports it from the cache.  This is great most of the time, because it means you don't have to re-load everything when a file changes.  the builder file never imports any of the other files, so it will never be cleared from the cache.  It can't import the schema file normally because that creates a circular dependency. By using a dynamic import, the dev server still registers that the builder file should be 
cleared (and by extension all the other files that define your schema) so your whole graph gets rebuilt.

**Comment by hayes** [comment]
One more thing you may need if you have custom plugins that you are editing: https://giraphql.com/api/schema-builder#schemabuilder-allowpluginreregistration

**Comment by pixelmund** [comment]
@hayes It seems like the esm folder wasn't published to npm, at least i can't see it in my node_modules folder.

**Comment by hayes** [comment]
Sorry, small oversight on my part on how the release script works.  Should be fixed now

**Comment by pixelmund** [comment]
The current Implementation of esm seems to be slightly wrong. It's working fine with vite in dev. But node still tries to import the cjs version. I think because of a missing export map in package.json. we would also need to add a package.json with type module in each esm folder. But this doesn't solve all problems because with type module every import must include the file extension e.g. `import Baz from './baz.js'`. I tried to make a pr to resolve those issues but we would need to edit every file accordingly or add a post build script/bundler which automatically adds them. I can still workaround it with the solution provided above but my array gets bigger and bigger and the ssr from vite is subject to change.

**Comment by hayes** [comment]
I think the way to handle this correctly is to use `.js` imports in the source typescript files.  This feels weird to me, but does seem to be supported.  Would need to update eslint to enforce this, and update the deno script to handle it correctly too.  Then we just need an exports block in package.json

**Comment by pixelmund** [comment]
Ahhh well that's a bit weird yes but seems more correct, didn't know that it's supported.

**Comment by hayes** [comment]
started working on this yesterday. Haven't really tested it yet https://github.com/hayes/giraphql/pull/122

**Comment by pixelmund** [comment]
amazing! i can easily test it if you like to publish a alpha or something

**Comment by hayes** [comment]
added preview versions.  I am trying out new snapshot releases using changesets.  Haven't really used them before, so not sure if there are issues with the 0.0.0 version that get used.  Versions are in the PR if you want to try them out.  I probably won't have time to get this properly tested until later in the weekend
